global:
  scrape_interval:     15s
  evaluation_interval: 15s
#  external_labels:
#    monitor: 'httpd-server'

scrape_configs:
  - job_name: 'httpd'
    static_configs:
      - targets: 
        - httpd:80
    metrics_path: /server-status
    scheme: http

    
