global:
  scrape_interval: 15s
  external_labels:
    monitor: 'httpd-server'

scrape_configs:
  - job_name: 'my_job'
    static_configs:
      - targets: ['localhost:']
    metrics_path: /server-status/?auto
    scheme: http
