global:
  scrape_interval: 15s
  external_labels:
    monitor: 'my-monitor'

scrape_configs:
  - job_name: 'httpd'
    static_configs:
      - targets: ['localhost:80']  

  - job_name: 'node'
    static_configs:
      - targets: ['localhost:9100']