version: '2.21.0'

networks:
  my_network:
    driver: bridge

services:

  wordpress:
    image: wordpress
    restart: always
    ports:
      - "8000:80"
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - /wordpress:/var/www/html
    networks:
      - my_network

  mariadb:
    image: mariadb
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    volumes:
      - /mariadb:/var/lib/mysql
    networks:
      - my_network

  httpd:
    image: httpd
    restart: always
    ports:
      - "8080:80"
    volumes:
      - /httpd:/usr/local/apache2/htdocs
    depends_on:
      - wordpress
    networks:
      - my_network
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
    networks:
      - my_network
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=yourpassword
    volumes:
      - ./grafana:/grafana
    depends_on:
      - prometheus
    networks:
      - my_network
