version: '2.21.0'

services:

  wordpress:
    image: wordpress
    restart: always
    ports:
      - "8000:80"
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - /wordpress:/var/www/html

  mariadb:
    image: mariadb
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    volumes:
      - /mariadb:/var/lib/mysql

  httpd:
    image: httpd
    restart: always
    ports:
      - "8080:80"
    volumes:
      - /httpd:/usr/local/apache2/htdocs
    depends_on:
      - wordpress
